### ISSUE TITLE
Allow access to the design repo

### ISSUE THREAD

**Issue by mjamescompton** [TheThingsNetwork/lorawan-devices#160]
#### Summary

Here the issue we have with design repo, this repository does not have rights to the private repo during a release.

```
Run cd website/
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/TheThingsIndustries/design.git
Directory: /home/runner/work/lorawan-devices/lorawan-devices/website
Output:
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

#### Why do we need this?

Make including the design repository easier

#### What is already there? What do you see now?

I've manually included the design repository files.

#### What is missing? What do you want to see?

design repository should be included via package.json and github actions should be given the right to pull.

#### How do you propose to implement this?

I'm thinking the solution will be something like this

```
- name: Checkout design repository
      uses: actions/checkout@v2
      with:
        repository: TheThingsIndustries/design
        token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
```

@johanstokking is it correct to give this public repository action access to a private repository? 

#### Can you do this yourself and submit a Pull Request?

yes, might need tokens and bots made for me
