### ISSUE TITLE
YAML long lines being prettified/reformatted by 'make validate fmt'

### ISSUE THREAD

**Issue by dmeehan1968** [TheThingsNetwork/lorawan-devices#387]
#### Summary

I've create a code YAML file for a device, in which the byte representation can grow quite large. 

The array syntax ([ and ]) extends beyond some number of items.  

When the file is processed with `make validate fmt`, the file is modified to break each element of the array across multiple lines (still using the [ and ] syntax, rather than YAML `-` syntax for each element.  Comments between elements are preserved.

#### What do you see now?

In this example, I have put line breaks after each 8 array elements, and in my code I have something similar with comments between lines so that I can remind myself of the byte order/purpose.

What the `fmt` command does it decide to split every array element onto its own line, although comments are preserved.

Before `make validate fmt`:
```YAML
uplinkDecoder:
  fileName: uplink.js
  examples:
    - description: First example
      input:
        bytes: [ 
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
          0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
          0x00, 0x00, 0x00, 0x00 
        ]
```

After `make validate fmt`:
```YAML
uplinkDecoder:
  fileName: uplink.js
  examples:
    - description: First example
      input:
        bytes: [ 
          0x00, 
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00, 
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00, 
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00,
          0x00, 
          0x00,
          0x00,
          0x00,
          0x00,
          0x00
        ]
```
...

#### What do you want to see instead?

The file should not be touched by validation.  This seems counter-intuitive as it would break versioning.

It seems that this is specifically what the `fmt` argument implies, but I don't see any reason to make this part of the functionality.  If YAML files are valid (and pass `validate`) then why do this?

It's not clear what induces this, some shorter arrays don't experience it.  The `prettier` command (run as a result of using the `fmt` arg) has a default 80 column wrap which may or may not be the cause.  It seems to be the number of elements in the array that matters, not the original formatting of the input YAML.

Whilst 'I' could choose to skip the `fmt` pass, one assumes that the pull request has this run automatically, thus changing my submission.  Even if this is not the case, anyone else running `fmt` on their own fork will cause my submission to be changed, and potentially incorporated into their own pull request (if they don't spot it).

It should be noted that `fmt` also processes javascript files.  I really do not see a purpose to this.  Why does the `prettier` command use the `--write` option?  It appears that its principally being used for validation of the YAML files.  Modifying the input files seems problematic.

...
